-- Smart Document Intake: invoice tables
-- Schema is also managed by EF Core migration "AddInvoiceTables" in the ExpenseTracker API project.

CREATE SCHEMA IF NOT EXISTS tracker_schema;

CREATE TABLE IF NOT EXISTS tracker_schema.invoices
(
    invoice_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number   varchar(50)    NOT NULL,
    supplier         varchar(200)   NOT NULL,
    invoice_date     date           NOT NULL,
    total_amount     numeric(18, 2) NOT NULL,
    source_file_name varchar(260)   NULL,
    created_at_utc   timestamptz    NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS tracker_schema.invoice_items
(
    invoice_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      integer        NOT NULL,
    description     varchar(500)   NOT NULL,
    quantity        numeric(18, 3) NOT NULL,
    unit_price      numeric(18, 2) NOT NULL,
    line_total      numeric(18, 2) NOT NULL,
    CONSTRAINT "FK_invoice_items_invoices_invoice_id"
        FOREIGN KEY (invoice_id)
        REFERENCES tracker_schema.invoices (invoice_id)
        ON DELETE CASCADE
);

-- Duplicate detection: an invoice number must be unique per supplier.
CREATE UNIQUE INDEX IF NOT EXISTS ux_invoices_number_supplier
    ON tracker_schema.invoices (invoice_number, supplier);

CREATE INDEX IF NOT EXISTS ix_invoices_supplier
    ON tracker_schema.invoices (supplier);

CREATE INDEX IF NOT EXISTS ix_invoices_invoice_date
    ON tracker_schema.invoices (invoice_date);

CREATE INDEX IF NOT EXISTS ix_invoice_items_invoice_id
    ON tracker_schema.invoice_items (invoice_id);
